<?php

return [
    // The Telegram BOT api token (use TELEGRAM_BOT_TOKEN for consistency with .env)
    'token' => env('TELEGRAM_BOT_TOKEN', env('TELEGRAM_TOKEN')),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations (api_url, is_local for Local Bot API Server)
    'config' => [
        'api_url' => env('TELEGRAM_BOT_API_URL', 'https://api.telegram.org'),
        'is_local' => (bool) env('TELEGRAM_BOT_API_IS_LOCAL', false),
        'storage_channel_id' => env('TELEGRAM_STORAGE_CHANNEL_ID'),
        'file_server_url' => rtrim(env('TELEGRAM_FILE_SERVER_URL', ''), '/'),
        'file_server_secret' => env('TELEGRAM_FILE_SERVER_SECRET', ''),
        'timeout' => (int) env('NUTGRAM_CLIENT_TIMEOUT', 60),
        'file_download_expires_minutes' => (int) env('TELEGRAM_FILE_DOWNLOAD_EXPIRES_MINUTES', 15),
    ],

    // Set if the service provider must load handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
